FROM node:19-alpine

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . .
ARG MONGODB_URI
ARG NAME
ARG SECRET
ARG PUBLIC_SITE_URL
ARG NEXTAUTH_URL
ARG smtpHost
ARG smtpPort
ARG smtpUser
ARG smtpPass
ARG privateKey
ARG BOT_TOKEN
ARG BOT_ID
ARG BOT_LOGIN
ARG PORT
ARG NUXT_HOST
ARG NUXT_PORT
ARG fkApiKey
ARG fkSecret1
ARG fkSecret2
ARG fkID
ARG SESSION_TOKEN
ARG serverLoadApiKey
ARG server_ip
ARG service_id
ARG VK_ACCESS_KEY
ARG VK_SECRET_KEY
ARG DOMAIN_API_IMAGES_URL
ARG CHANGING_PROXY
ARG SECOND_CHANGING_PROXY
ARG ORGANIZATION_KEY
ARG HI_CALL_KEY
ARG WB_DB_URI
ARG OZON_DB_URI
ARG FLOWWOW_DB_URI
ARG YANDEX_MAPS_API_KEY
ARG ZVONOK_PUBLIC_KEY
ARG ZVONOK_CAMPAIGN_ID
ARG AVITO_DB_URI
ARG DADATA_TOKEN
ARG DADATA_SECRET
ARG PARSER_TOKEN
ARG OZON_PVZ_DB_URI

ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV MONGODB_URI=${MONGODB_URI}
ENV SESSION_TOKEN=${SESSION_TOKEN}
ENV NAME=${NAME}
ENV SECRET=${SECRET}
ENV PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV smtpHost=${smtpHost}
ENV smtpPort=${smtpPort}
ENV smtpUser=${smtpUser}
ENV smtpPass=${smtpPass}
ENV privateKey=${privateKey}
ENV BOT_TOKEN=${BOT_TOKEN}
ENV BOT_ID=${BOT_ID}
ENV BOT_LOGIN=${BOT_LOGIN}
ENV PORT=${PORT}
ENV NUXT_HOST=${NUXT_HOST}
ENV NUXT_PORT=${NUXT_PORT}
ENV fkApiKey=${fkApiKey}
ENV fkSecret1=${fkSecret1}
ENV fkSecret2=${fkSecret2}
ENV fkID=${fkID}
ENV serverLoadApiKey=${serverLoadApiKey}
ENV server_ip=${server_ip}
ENV service_id=${service_id}
ENV VK_ACCESS_KEY=${VK_ACCESS_KEY}
ENV VK_SECRET_KEY=${VK_SECRET_KEY}
ENV DOMAIN_API_IMAGES_URL=${DOMAIN_API_IMAGES_URL}
ENV CHANGING_PROXY=${CHANGING_PROXY}
ENV SECOND_CHANGING_PROXY=${SECOND_CHANGING_PROXY}
ENV ORGANIZATION_KEY=${ORGANIZATION_KEY}
ENV HI_CALL_KEY=${HI_CALL_KEY}
ENV WB_DB_URI=${WB_DB_URI}
ENV OZON_DB_URI=${OZON_DB_URI}
ENV YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
ENV ZVONOK_PUBLIC_KEY=${ZVONOK_PUBLIC_KEY}
ENV ZVONOK_CAMPAIGN_ID=${ZVONOK_CAMPAIGN_ID}
ENV AVITO_DB_URI=${AVITO_DB_URI}
ENV DADATA_TOKEN=${DADATA_TOKEN}
ENV DADATA_SECRET=${DADATA_SECRET}
ENV FLOWWOW_DB_URI=${FLOWWOW_DB_URI}
ENV PARSER_TOKEN=${PARSER_TOKEN}
ENV OZON_PVZ_DB_URI=${OZON_PVZ_DB_URI}

RUN npm install -g pnpm
RUN apk add --no-cache python3 make g++
RUN pnpm install
RUN pnpm run build
ENV NODE_ENV production
ENV PORT 80

EXPOSE 80 

ENTRYPOINT ["node", ".output/server/index.mjs"]
